# 1. Create a null vector of size 10 but the fifth value which is 1.
import numpy as np


In [2]:
a=np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
a=np.random.randint(1,10,8)

In [5]:
a

array([8, 6, 9, 8, 8, 3, 7, 3])

In [8]:
a=np.zeros((10), dtype=int) 
a[4]=1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

# 2. Create a vector with values ranging from 10 to 49.
x=np.arange(10,49)

In [10]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

# 3. Create a 3x3 matrix with values ranging from 0 to 8

y=np.arange(0,8)

In [23]:
y

array([0, 1, 2, 3, 4, 5, 6, 7])

In [29]:
np.random.randint(0,8,(3,3))

array([[3, 1, 1],
       [4, 0, 3],
       [1, 1, 2]])

# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

x=np.array([1,2,0,0,4,0])
x

In [34]:
np.nonzero(x)

(array([0, 1, 4], dtype=int64),)

 # 5. Create a 10x10 array with random values and find the minimum and maximum values.
 
 m=np.random.randint(1,100,(10,10))
 

In [44]:
m

array([[23, 24, 23, 91, 72, 37, 36, 80, 33, 89],
       [ 6, 15, 52, 49, 76,  4, 63, 41, 22, 10],
       [85, 57, 98, 18, 80, 84, 16, 38, 68, 12],
       [12, 35, 96, 47, 45, 28, 84, 33, 63, 42],
       [52,  2, 19, 27, 96, 42, 99, 94, 14, 46],
       [83, 87, 98, 62, 49, 55, 68, 47, 70, 25],
       [82, 64, 73, 88, 81, 37, 60, 26, 29, 17],
       [ 4, 57, 95,  2,  6, 81, 97, 91, 34, 85],
       [39, 23, 16, 74, 84, 96, 33, 66, 76, 75],
       [88, 59, 38, 51, 73, 75, 96, 80, 96, 82]])

In [45]:
print(np.min(m))
print(np.max(m))

2
99


# 6. Create a random vector of size 30 and find the mean value.


In [52]:

p=np.random.random(30)
p


array([0.90749557, 0.77546563, 0.6948138 , 0.75186888, 0.37215348,
       0.36742361, 0.54939441, 0.92610504, 0.5672032 , 0.12133117,
       0.49873643, 0.27933452, 0.04907853, 0.62581116, 0.94480512,
       0.51561632, 0.04417807, 0.7664664 , 0.78360277, 0.65879161,
       0.47351927, 0.66428994, 0.60043336, 0.52191932, 0.41085369,
       0.31621481, 0.43294133, 0.5640602 , 0.4764859 , 0.91682693])

In [53]:
p.mean()

0.5525740153134513